export default {
    name: 'custom',
    type: {
        positive: 'ri:check-line',
        negative: 'ri:alert-line',
        info: 'ri:info-i',
        warning: 'ri:spam-line',
    },
    arrow: {
        up: 'ri:arrow-up-line',
        right: 'ri:arrow-right-line',
        down: 'ri:arrow-down-line',
        left: 'ri:arrow-left-line',
        dropdown: 'eva-arrow-down-outline',
    },
    chevron: {
        left: 'ri:arrow-left-s-line',
        right: 'ri:arrow-right-s-line',
    },
    colorPicker: {
        spectrum: 'ri:palette-line',
        tune: 'ri:color-filter-line',
        palette: 'ri:pantone-line',
    },
    pullToRefresh: {
        icon: 'ri:refresh-line',
    },
    carousel: {
        left: 'mdi-chevron-left',
        right: 'mdi-chevron-right',
        up: 'mdi-chevron-up',
        down: 'mdi-chevron-down',
        navigationIcon: 'ri:circle-fill',
    },
    chip: {
        remove: 'ri:close-circle-fill',
        selected: 'ri:check-line',
    },
    datetime: {
        arrowLeft: 'mdi-chevron-left',
        arrowRight: 'mdi-chevron-right',
        now: 'ri:time-line',
        today: 'ri:calendar-event-line',
    },
    editor: {
        bold: 'ri:bold',
        italic: 'ri:italic',
        strikethrough: 'ri:strikethrough',
        underline: 'ri:underline',
        unorderedList: 'ri:list-check',
        orderedList: 'ri:list-ordered-2',
        subscript: 'ri:subscript',
        superscript: 'ri:superscript',
        hyperlink: 'ri:link-m',
        toggleFullscreen: 'ri:fullscreen-line',
        quote: 'ri:double-quotes-r',
        left: 'ri:align-left',
        center: 'ri:align-center',
        right: 'ri:align-right',
        justify: 'ri:align-justify',
        print: 'ri:printer-line',
        outdent: 'ri:indent-decrease',
        indent: 'ri:indent-increase',
        removeFormat: 'ri:format-clear',
        formatting: 'ri:text',
        fontSize: 'ri:font-size',
        align: 'ri:align-left',
        hr: 'ri:subtract-line',
        undo: 'ri:corner-up-left-line',
        redo: 'ri:corner-up-right-line',
        heading: 'ri:font-size-2',
        heading1: 'mdi-format-header-1',
        heading2: 'mdi-format-header-2',
        heading3: 'mdi-format-header-3',
        heading4: 'mdi-format-header-4',
        heading5: 'mdi-format-header-5',
        heading6: 'mdi-format-header-6',
        code: 'ri:code-s-slash-line',
        size: 'ri:font-size-2',
        size1: 'mdi-numeric-1-box',
        size2: 'mdi-numeric-2-box',
        size3: 'mdi-numeric-3-box',
        size4: 'mdi-numeric-4-box',
        size5: 'mdi-numeric-5-box',
        size6: 'mdi-numeric-6-box',
        size7: 'mdi-numeric-7-box',
        font: 'mdi-format-font',
        viewSource: 'mdi-code-tags',
    },
    expansionItem: {
        icon: 'eva-arrow-down-outline',
        denseIcon: 'eva-arrow-down-outline',
    },
    fab: {
        icon: 'ri:add-line',
        activeIcon: 'ri:close-line',
    },
    field: {
        clear: 'ri:close-line',
        error: 'ri:error-warning-line',
    },
    pagination: {
        first: 'mdi-chevron-double-left',
        prev: 'mdi-chevron-left',
        next: 'mdi-chevron-right',
        last: 'mdi-chevron-double-right',
    },
    rating: {
        icon: 'mdi-star',
    },
    stepper: {
        done: 'ri:check-line',
        active: 'eva-edit-2-outline',
        error: 'ri:alert-line',
    },
    tabs: {
        left: 'mdi-chevron-left',
        right: 'mdi-chevron-right',
        up: 'mdi-chevron-up',
        down: 'mdi-chevron-down',
    },
    table: {
        arrowUp: 'mdi-arrow-up',
        warning: 'ri:alert-line',
        firstPage: 'mdi-chevron-double-left',
        prevPage: 'mdi-chevron-left',
        nextPage: 'mdi-chevron-right',
        lastPage: 'mdi-chevron-double-right',
    },
    tree: {
        icon: 'eva-arrow-right-outline',
    },
    uploader: {
        done: 'ri:check-line',
        clear: 'ri:close-line',
        add: 'ri:add-line',
        upload: 'ri:upload-cloud-2-lined',
        removeQueue: 'eva-trash-outline',
        removeUploaded: 'ri:check-double-line',
    },
};
